SEED_LEADS = [
    {
        "lead_id": "energy-lead-001",
        "vertical": "energy",
        "customer_label": "Priya Sharma",
        "test_phone": "+61 400 000 101",
        "synthetic": True,
        "dnc_status": "clear",
        "journey_status": "dropped_off",
        "last_completed_step": "postcode",
        "next_step": "property_type",
        "captured_fields": {"postcode": "3000"},
        "consent_status": "not_requested",
        "outcome": None,
    },
    {
        "lead_id": "energy-lead-002",
        "vertical": "energy",
        "customer_label": "Daniel Hughes",
        "test_phone": "+61 400 000 102",
        "synthetic": True,
        "dnc_status": "clear",
        "journey_status": "dropped_off",
        "last_completed_step": "property_type",
        "next_step": "current_provider",
        "captured_fields": {"postcode": "4000", "property_type": "house"},
        "consent_status": "not_requested",
        "outcome": None,
    },
    {
        "lead_id": "energy-lead-003",
        "vertical": "energy",
        "customer_label": "Aarav Mehta",
        "test_phone": "+61 400 000 103",
        "synthetic": True,
        "dnc_status": "clear",
        "journey_status": "dropped_off",
        "last_completed_step": "postcode",
        "next_step": "property_type",
        "captured_fields": {"postcode": "5000"},
        "consent_status": "not_requested",
        "outcome": None,
    },
    {
        "lead_id": "energy-lead-004",
        "vertical": "energy",
        "customer_label": "Sophie Martin",
        "test_phone": "+61 400 000 104",
        "synthetic": True,
        "dnc_status": "clear",
        "journey_status": "dropped_off",
        "last_completed_step": "property_type",
        "next_step": "usage_pattern",
        "captured_fields": {"postcode": "2000", "property_type": "unit"},
        "consent_status": "not_requested",
        "outcome": None,
    },
    {
        "lead_id": "energy-lead-005",
        "vertical": "energy",
        "customer_label": "Michael Chen",
        "test_phone": "+61 400 000 105",
        "synthetic": True,
        "dnc_status": "clear",
        "journey_status": "dropped_off",
        "last_completed_step": "usage_pattern",
        "next_step": "plan_preferences",
        "captured_fields": {"postcode": "6000", "usage_pattern": "standard"},
        "consent_status": "not_requested",
        "outcome": None,
    },
    {
        "lead_id": "energy-lead-006",
        "vertical": "energy",
        "customer_label": "Emily Taylor",
        "test_phone": "+61 400 000 106",
        "synthetic": True,
        "dnc_status": "clear",
        "journey_status": "dropped_off",
        "last_completed_step": "current_provider",
        "next_step": "usage_pattern",
        "captured_fields": {"postcode": "7000", "current_provider": "AGL"},
        "consent_status": "not_requested",
        "outcome": None,
    },
    {
        "lead_id": "energy-lead-007",
        "vertical": "energy",
        "customer_label": "Olivia Wilson",
        "test_phone": "+61 400 000 107",
        "synthetic": True,
        "dnc_status": "clear",
        "journey_status": "dropped_off",
        "last_completed_step": "postcode",
        "next_step": "property_type",
        "captured_fields": {"postcode": "2600"},
        "consent_status": "not_requested",
        "outcome": None,
    },
    {
        "lead_id": "energy-lead-008",
        "vertical": "energy",
        "customer_label": "Noah Brown",
        "test_phone": "+61 400 000 108",
        "synthetic": True,
        "dnc_status": "clear",
        "journey_status": "dropped_off",
        "last_completed_step": "property_type",
        "next_step": "current_provider",
        "captured_fields": {"postcode": "0800", "property_type": "house"},
        "consent_status": "not_requested",
        "outcome": None,
    },
]

ENERGY_FIELD_ORDER = [
    "postcode",
    "property_type",
    "current_provider",
    "usage_pattern",
    "plan_preferences",
]

FIELD_LABELS = {
    "postcode": "Postcode",
    "property_type": "Property type",
    "current_provider": "Current provider",
    "usage_pattern": "Usage pattern",
    "plan_preferences": "Plan preferences",
}
